### ISSUE TITLE
WAF not serving CA

### ISSUE THREAD

**Issue by Z3nto** [rklomp/sophos-utm-letsencrypt#1]
Hi,

in the readme you write i just need to install the CA in Webserver Protection -> Certificate Management -> Certificate Authority. I've done this but the WAF is not serving it with  the Let's encrypt certs.

Do u have any additional idea for me?

[http://i.imgur.com/g79qNUQ.png](http://i.imgur.com/g79qNUQ.png)

BR Z3nto

**Comment by TacticalCode** [comment]
I also had the issue that my new Certificate wasn't served in a chain bundle with the intermediate cert.
This was some weeks ago, so I don't exactly remember, but I think the WAF serves just the domain cert, unless the real webserver also returns the intermediate cert. I was rather confused why changing the certificate bundle on the real webserver had any effect on the Sophos-Terminated SSL connections, but that seems to work for me.
Workaround might be deploying the proper certificate chain to your real webserver.

**Comment by rklomp** [comment]
I have seen the same issue also with backend server without ssl. Currently I think it might have something to do with the link between the ca cert and domain cert. I will try to reproduce the issue and find a solution.

**Comment by trollvottel** [comment]
Try to **append** the intermediate-ca-cert to the host-cert and import that as the 'host_key_cert'.

FYI: Firefox tricks you into thinking the chain is setup correctly because it caches the intermediate-ca-cert, it may also have been seen already by visiting another letsencrypt-signed site... You better use https://www.ssllabs.com/ssltest/ to check.

BTW: WebAdmin itself does not serve the chain either. A well-known, long-standing bug in Sophos UTM.

**Comment by ghost** [comment]
Hi Rene, thanks for your great work.
I think the way trollvottel described would be a really good solution.
Simply importing full_chain (appended <domain>.crt + chain.crt).
Another solution would be to let getssl create fullchain.crt or fullchain.pem and import these directly.
https://github.com/srvrco/getssl/issues/27
This can be achieved via using parameter:
#DOMAIN_CHAIN_LOCATION="" this is the domain cert and CA cert
#DOMAIN_PEM_LOCATION="" this is the domain_key. domain cert and CA cert

Maybe you can change your script accordingly to use these to import to UTM.
