### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Atreyu79** [rklomp/sophos-utm-letsencrypt#15]
Dear sir.  Lately I've been receiving this error when performing ./getssl -f <domain>  I've never had this issue before recently.  Not sure if it's just me, but thought I should let you know.  All of my configs look right (they haven't changed).

```
reloading SSL services
Traceback (most recent call last):
  File "/root/update-cert", line 119, in <module>
    main()
  File "/root/update-cert", line 108, in main
    if (len(sys.argv[3]) > 1):
IndexError: list index out of range
getssl: error running /root/update-cert <domain> REF_<ref>
```

**Comment by Atreyu79** [comment]
I used one of your previous versions, and it seems to work fine.

This is the one I tried:
wget **https://raw.githubusercontent.com/rklomp/sophos-utm-letsencrypt/1cd53b7b9c5ee95c75d7df2b3679a02c1b4eb897/update-cert** --no-check-certificate

**Comment by scottsisco** [comment]
I get the same error and can confirm the version Atreyu79 works.

**Comment by oleolafson** [comment]
Same error here, my workaround is to put the path "/root/" at the end of the RELOAD_CMD line, so that it reads
RELOAD_CMD="/root/update-cert yourdomain.com REF_CaHosLetsEncryp /root/" 
instead of 
RELOAD_CMD="/root/update-cert yourdomain.com REF_CaHosLetsEncryp"

**Comment by GilchristT** [comment]
> Same error here, my workaround is to put the path "/root/" at the end of the RELOAD_CMD line

Thanks @oleolafson That fixed this for me
