### ISSUE TITLE
Domain Issue

### ISSUE THREAD

**Issue by ghost** [rklomp/sophos-utm-letsencrypt#17]
I'm very new to Sophos and certificates but looking in the guide where it says "domain.com" what do I put their, do I put my Sophos router IP or what?

**Comment by GilchristT** [comment]
Same question here. I want a certificate with the DN smtp.xyz.com as I'm really only going to be using the UTM for SMTP spam filtering initially.

Where the documentation refers to "yourdomain.com" should I be entering "xyz.com" or "smtp.xyz.com"?

I'm off to try both approaches but it might be worth clarifying in the documentation if at least two of us are confused :-)

Thanks for the script BTW, great work.
