### ISSUE TITLE
update-cert fail

### ISSUE THREAD

**Issue by angelkiller2** [rklomp/sophos-utm-letsencrypt#3]
Hello,

i had done the setup and i receive cert from letsencrypt. But the update-cert fails with this error:

`rs:/root # ./getssl -f mydomain.de
Registering account
Verify each domain
Verifying mydomain.de
mydomain.de is already validated
Verification completed, obtaining certificate.
Certificate saved in /root/.getssl/mydomain.de/mydomain.de.crt
The intermediate CA cert is in /root/.getssl/mydomain.de/chain.crt
reloading SSL services
  File "/root/update-cert", line 34
    return value.split('/')[-1]
         ^
IndentationError: expected an indented block
getssl: error running /root/update-cert mydomain REF_CaHosmydomainde
rs:/root #
`
Any hints on this?

**Comment by rklomp** [comment]
Can you re-download the file and try again?

**Comment by angelkiller2** [comment]
1. Yes, many thanks! Here the new ouput:

rs:/root # ./getssl -f mydomain.de Registering account Verify each domain Verifying mydomain.de mydomain.de is already validated Verification completed, obtaining certificate. Certificate saved in /root/.getssl/mydomain.de/mydomain.de.crt The intermediate CA cert is in /root/.getssl/mydomain.de/chain.crt reloading SSL services Writing certificate for mydomain.de to object REF_CaHosmydomainde Updating certificate meta to object REF_CaMetCnmydomain Done! mydomain.de - certificate installed OK on server certificate obtained for mydomain.de
