### ISSUE TITLE
Sophos UTM doesn't have an FTP client?

### ISSUE THREAD

**Issue by azuntik** [rklomp/sophos-utm-letsencrypt#4]
I'm running firmware version 9.410-6. I was able to follow your instructions without any problem until I got to setting the ACL. I can't seem to SSH from Sophos to my webserver, so I thought I'd give FTP a shot. No dice. I don't know if it's just my version of UTM, but line 541 of the getssl script errors out with command not found. I dug through everywhere I could think of trying to find an FTP client preinstalled or how to get one on there, but I came up empty.

As for SSH, it always times out. No idea why. I can SSH from other systems just fine.

So, no SSH, no FTP. Any ideas?

**Comment by rklomp** [comment]
You are right. The Sophos does not have a ftp executable by default, but you might be able to install/compile one yourself. I have not tried that.

Regarding SSH, you should add a outbound firewall rule to allow the UTM to connect to the machine. Check your firewall log for dropped flows.
