### ISSUE TITLE
Problems with renewing, Windows Server

### ISSUE THREAD

**Issue by remco770** [rklomp/sophos-utm-letsencrypt#5]
Hello,

Not sure if it's a real issue, but maybe someone can help me out.

I followed the tutorial, and the challange can be copied by SSH. But i'm using a Windows server, so I should use the FTP option. But I can't find a tutorial to install a FTP Client to the Sophos UTM firewall.

Can someone help me out?

Remco

**Comment by stephenc01** [comment]
You can try to use sftp with FileZilla, it's essentially ftp over ssh. Otherwise you can use putty.

**Comment by remco770** [comment]
I'm not sure you understand me correctly

I'm refering to the following part of your tutorial:

"Note: If you use SSH you need to create a ssh-key using ssh-keygen and copy it to your server ssh-copy-id <user>@<server>

Tip: If you cannot copy the file to the server serving this domain you can copy it to another server and use Site Path Routing for path /.well-known/acme-challenge/ to this other server.

Tip2: Using FTP is also possible, see the example in the config file, but an FTP excutable is not available by default on the Sophos UTM."

TIP2 is using FTP, I need a FTP client at the Sophos UTM. The FTP executable is missing, how can I set it up? 

Thankyou.

**Comment by stephenc01** [comment]
Yes, I read it backwards. 

These directions will give you a ssh server on windows. 
https://winscp.net/eng/docs/guide_windows_openssh_server

**Comment by sturze** [comment]
hi @remco770 
if you say windows, i assume you are running iis on windows, right?
how have you managed iis to load the certificates you loaded onto it, to get validated?
