### ISSUE TITLE
[understanding]  http://yourdomain.com/.well-known/acme-challenge/  reachable

### ISSUE THREAD

**Issue by maxhoheiser** [rklomp/sophos-utm-letsencrypt#9]
I dont quite understand what is ment with the website  http://yourdomain.com/.well-known/acme-challenge/  must be reachable from the utm. Do I have to install a webserver on the target machine for the domain and serve this website?
Because I want to have only subdomains which point to a nextcloud and a collabora docker container.

**Comment by rklomp** [comment]
<your-domain-name-here>/.well-known/acme-challenge/ should be reachable from the internet.

For more information refer to the acme documentation:
https://ietf-wg-acme.github.io/acme/#rfc.section.8.3
